#!/usr/bin/env bash
# Double the number of webservers

print_info() {
    local subdomain=$1
    local domain=$2

    echo "$(dig $subdomain.$domain | awk '/ANSWER SECTION:/ {getline; print "The subdomain '"$subdomain"' is a "$4" record and points to "$5}')"
}

if [ "$#" -eq 1 ];
    then
    print_info "$2.$1" "$2"
else
    print_info "www.$1" "www"
    print_info "lb-01.$1" "lb-01"
    print_info "web-01.$1" "web-01"
    print_info "web-02.$1" "web-02"
fi
