#!/usr/bin/env bash
#Install nginx web server

sudo apt-get update -y
sudo apt-get install nginx -y

sudo echo "Hello World!" | tee /var/www/html/index.nginx-debian.html > /dev/null
sudo echo "Ceci n'est pas une page" | tee /var/www/html/404.html > /dev/null
ServerBlock="server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

}"

sudo echo "$ServerBlock" | tee /etc/nginx/sites-available/default > /dev/null
sudo service nginx restart
