#!/usr/bin/env bash
#installs nginx and configure it to listen on port 80
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-site0.html
sudo service nginx start
