#!/usr/bin/env bash
#Install nginx web server

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

ServerBlock="server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    add_header X-Served-By \$HOSTNAME;
}"


echo "$ServerBlock" |sudo  tee /etc/nginx/sites-available/default > /dev/null
sudo service nginx restart
