#!/usr/bin/env bash
# Displays 'Best School'. Displays "bad luck" on the 5th iteration and "good luck" on the 9th iteration

i=0

while [ $i -lt 10 ]; do
  if [ $i -eq 4 ]; then
    echo "bad luck"
  elif [ $i -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done
