#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:

i=1
while [ $i -le 20 ]
do
    case $i in 
    4)
        echo -e "$i\nbad luck from China"
        ;;
    9)
        echo -e "$i\nbad luck from Japan"
        ;;
    17)
        echo -e "$i\nbad luck from Italy"
        ;;
    *)
        echo "$i"
        ;;
    esac
    (( i++ ))
done